apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0  # Temporalmente usar root para debug
      containers:
        - name: laravel
          image: us-central1-docker.pkg.dev/ftrick-455901/ftrick-laravel/ftrick-laravel:latest
          ports:
            - containerPort: 80
          # Elimina envFrom si decides usar la opción de montaje
          # envFrom:
          #   - secretRef:
          #       name: laravel-env
          volumeMounts:
            - name: php-logs
              mountPath: /var/log/php-fpm
            - name: env-file
              mountPath: /var/www/.env
              subPath: .env
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: php-logs
          emptyDir: {}
        - name: env-file
          secret:
            secretName: laravel-env
            items:
              - key: .env
                path: .env