apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  labels:
    app: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0  # Temporalmente usar root para debug
      containers:
        - name: laravel
          image: us-central1-docker.pkg.dev/ftrick-455901/ftrick-laravel/ftrick-laravel:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: laravel-env
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: php-logs
              mountPath: /var/log/php-fpm
            # Añadir esta sección para la configuración de Nginx
            - name: nginx-config
              mountPath: /etc/nginx/sites-enabled/default
              subPath: default.conf
      volumes:
        - name: php-logs
          emptyDir: {}
        # Añadir este volumen para la configuración de Nginx
        - name: nginx-config
          configMap:
            name: nginx-config