apiVersion: v1
kind: Secret
metadata:
  name: laravel-env
  namespace: default
  labels:
    argocd.argoproj.io/instance: laravel-app
type: Opaque
stringData:
  APP_NAME: "Laravel"
  APP_ENV: "production"
  APP_KEY: "base64:izjqzq11S1oQf/9lupB/Wh/InfnV8EO5DEeLQi3CEaQ="
  APP_DEBUG: "false"
  APP_URL: "http://104.154.249.213"
  
  DB_CONNECTION: "mysql"
  DB_HOST: "10.51.0.3"
  DB_PORT: "3306"
  DB_DATABASE: "my_database"
  DB_USERNAME: "db_user"
  DB_PASSWORD: "my_secure_password"
  
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
